"""
match_pbac_nice.py
━━━━━━━━━━━━━━━━━━
Cross-references PBAC Public Summary Documents with NICE Technology Appraisals
to produce a side-by-side comparison dataset: same drug, two countries, two dates.

KEY OUTPUTS:
  pbac_nice_matched.csv     — matched pairs with:
                              drug, pbac_date, nice_date, gap_days, gap_months,
                              who_moved_first, pbac_outcome, nice_recommendation
  pbac_nice_unmatched.csv   — PSDs with no NICE TA match (AUS-only approvals)
  nice_pbac_unmatched.csv   — NICE TAs with no PBAC match (UK-only approvals)

ANALYSIS QUESTIONS THIS ENABLES:
  - How many months does Australia lag behind the UK for the same drug?
  - Are PBAC and NICE concordant? (both recommend / both reject / split)
  - Which therapy areas have the biggest access gaps?
  - For which drugs did Australia actually move first?

REQUIREMENTS:
  - nice_metadata.csv (generated by download_nice_missing.py OR manually created)
  - The PSD_database folder with PBAC PSDs (*.pdf files named {drug}-psd-*.pdf)

  pip install thefuzz python-Levenshtein  (for fuzzy matching — optional but better)

USAGE:
  python match_pbac_nice.py
  python match_pbac_nice.py --psd-dir /path/to/PSDs --nice-meta nice_metadata.csv

MATCHING APPROACH:
  1. Exact match: normalised drug name (lowercase, remove spaces/hyphens)
  2. Prefix match: PBAC name starts with NICE name or vice versa (handles brand/generic)
  3. Fuzzy match (if thefuzz installed): Levenshtein similarity ≥ 85%
  4. Manual overrides: edit MANUAL_ALIASES below for known mismatches
"""

from __future__ import annotations

import csv
import re
import sys
import argparse
import logging
from pathlib import Path
from datetime import datetime, date
from collections import defaultdict

# Optional fuzzy matching
try:
    from thefuzz import fuzz
    FUZZY_AVAILABLE = True
except ImportError:
    FUZZY_AVAILABLE = False

# ── config ────────────────────────────────────────────────────────────────────
_HERE      = Path(__file__).parent
PSD_DIR    = _HERE            # PBAC PSDs live in same folder as this script
META_PATH  = _HERE / "nice_metadata.csv"
OUT_DIR    = _HERE

FUZZY_THRESHOLD = 85   # % similarity for fuzzy match

# Manual aliases: maps a PBAC drug name token → NICE drug name token (or vice versa)
# Add entries here when the automated matcher misses obvious pairs.
MANUAL_ALIASES: dict[str, str] = {
    "pembrolizumab":    "pembrolizumab",
    "trastuzumab-emtansine": "trastuzumab emtansine",
    "ado-trastuzumab":  "trastuzumab emtansine",
    "sacubitril-valsartan": "sacubitril",
    "budesonide-formoterol": "budesonide",
    "fluticasone-salmeterol": "fluticasone",
    "elexacaftor-tezacaftor-ivacaftor": "elexacaftor",
    "bictegravir-emtricitabine-tenofovir": "bictegravir",
    "dolutegravir-lamivudine": "dolutegravir",
    "cabotegravir-rilpivirine": "cabotegravir",
}

MONTH_MAP = {
    "jan":1,"january":1,"feb":2,"february":2,"mar":3,"march":3,
    "apr":4,"april":4,"may":5,"jun":6,"june":6,
    "jul":7,"july":7,"aug":8,"august":8,"sep":9,"september":9,
    "oct":10,"october":10,"nov":11,"november":11,"dec":12,"december":12,
}

# ── logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)


# ── date parsing ──────────────────────────────────────────────────────────────
def parse_nice_date(s: str) -> "date | None":
    """Parse NICE published_date strings like '29 March 2017', 'March 2017', '2017'."""
    if not s:
        return None
    s = s.strip()

    # "29 March 2017"
    m = re.match(r"(\d{1,2})\s+(\w+)\s+(\d{4})", s)
    if m:
        mo = MONTH_MAP.get(m.group(2).lower())
        if mo:
            try:
                return date(int(m.group(3)), mo, int(m.group(1)))
            except ValueError:
                pass

    # "March 2017"
    m = re.match(r"(\w+)\s+(\d{4})", s)
    if m:
        mo = MONTH_MAP.get(m.group(1).lower())
        if mo:
            return date(int(m.group(2)), mo, 15)  # mid-month approximation

    # "2017"
    m = re.match(r"(\d{4})$", s)
    if m:
        return date(int(m.group(1)), 7, 1)  # mid-year approximation

    return None


def parse_pbac_date(year: int, month: "int | None") -> "date | None":
    """Convert PBAC year + month (from filename) to a date."""
    if year is None:
        return None
    if month is None:
        return date(year, 7, 1)   # mid-year approximation
    # PBAC meeting months are 3 (March), 7 (July), 11 (November)
    # PSDs are published ~4 months after the meeting, so the listing date
    # is approximately meeting month + 4. We record the meeting date.
    return date(year, month, 1)


# ── PBAC PSD parsing ──────────────────────────────────────────────────────────
def parse_pbac_psds(psd_dir: Path) -> list[dict]:
    """
    Parse all {drug}-psd-{month}-{year}.pdf files in psd_dir.
    Returns list of dicts: filename, drug, year, month, pbac_date.
    """
    records = []
    for f in sorted(psd_dir.glob("*.pdf")):
        if "psd" not in f.name.lower():
            continue

        s = f.name.lower().replace("%20", "-").replace(" ", "-")
        s = re.sub(r"\.pdf$", "", s)

        # Extract drug name (everything before -psd)
        m = re.match(r"^(.+?)-psd", s)
        drug = m.group(1).strip("-") if m else s

        # Extract date
        year, month = None, None
        m2 = re.search(r"-psd[^-]*-([a-z]+)-(\d{4})", s)
        if m2:
            mo = MONTH_MAP.get(m2.group(1))
            yr = int(m2.group(2))
            if mo and 2000 <= yr <= 2030:
                year, month = yr, mo
        if year is None:
            m3 = re.search(r"-psd[^-]*-(\d{1,2})-(\d{4})", s)
            if m3:
                mo, yr = int(m3.group(1)), int(m3.group(2))
                if 1 <= mo <= 12 and 2000 <= yr <= 2030:
                    year, month = yr, mo
        if year is None:
            m4 = re.search(r"-psd[^-]*-(\d{4})", s)
            if m4:
                yr = int(m4.group(1))
                if 2000 <= yr <= 2030:
                    year = yr
        if year is None:
            m5 = re.search(r"(\d{4})-(\d{2})(?:-final)?$", s)
            if m5:
                yr, mo = int(m5.group(1)), int(m5.group(2))
                if 2000 <= yr <= 2030 and 1 <= mo <= 12:
                    year, month = yr, mo

        if year is None:
            continue

        records.append({
            "filename":   f.name,
            "drug":       drug,
            "year":       year,
            "month":      month,
            "pbac_date":  parse_pbac_date(year, month),
        })

    return records


def load_nice_metadata(meta_path: Path) -> list[dict]:
    """Load nice_metadata.csv and parse dates."""
    if not meta_path.exists():
        log.error(f"nice_metadata.csv not found at: {meta_path}")
        log.error("Run download_nice_missing.py first to generate it.")
        return []

    records = []
    with open(meta_path, encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            row["nice_date"] = parse_nice_date(row.get("published_date", ""))
            row["ta_number"] = int(row["ta_number"]) if row.get("ta_number") else 0
            records.append(row)
    return records


# ── drug name normalisation ───────────────────────────────────────────────────
def normalise(name: str) -> str:
    """Lowercase, remove hyphens/spaces/punctuation, apply aliases."""
    n = name.lower().strip()
    # Apply manual aliases first
    for alias_from, alias_to in MANUAL_ALIASES.items():
        if alias_from in n:
            n = alias_to
            break
    # Remove hyphens and whitespace
    n = re.sub(r"[\s\-]+", "", n)
    # Remove common suffixes that differ between countries
    n = re.sub(r"(alfa|beta|gamma|delta|hydro|sodium|chloride|acetate|phosphate|sulphate|sulfate)$", "", n)
    return n


# ── matching ──────────────────────────────────────────────────────────────────
def match_drug(pbac_drug: str, nice_records: list[dict]) -> "list[dict]":
    """
    Find all NICE records that match a PBAC drug name.
    Returns list of matching NICE records (there may be multiple TAs for one drug).
    """
    p_norm = normalise(pbac_drug)
    matches = []

    for nr in nice_records:
        n_norm = normalise(nr.get("drug_name", ""))
        if not n_norm:
            continue

        # 1. Exact match
        if p_norm == n_norm:
            matches.append(nr)
            continue

        # 2. Prefix match (one is a prefix of the other)
        shorter, longer = (p_norm, n_norm) if len(p_norm) <= len(n_norm) else (n_norm, p_norm)
        if len(shorter) >= 4 and longer.startswith(shorter):
            matches.append(nr)
            continue

        # 3. Substring match (for compound drug names, e.g. sacubitril-valsartan)
        if len(p_norm) >= 6 and p_norm in n_norm:
            matches.append(nr)
            continue
        if len(n_norm) >= 6 and n_norm in p_norm:
            matches.append(nr)
            continue

        # 4. Fuzzy match
        if FUZZY_AVAILABLE and len(p_norm) >= 5 and len(n_norm) >= 5:
            score = fuzz.ratio(p_norm, n_norm)
            if score >= FUZZY_THRESHOLD:
                matches.append(nr)

    return matches


# ── gap calculation ────────────────────────────────────────────────────────────
def date_gap(pbac_date: "date | None", nice_date: "date | None") -> "tuple[int | None, float | None, str]":
    """
    Returns (gap_days, gap_months, who_moved_first).
    Positive gap means NICE was first (Australia lagged).
    Negative gap means PBAC was first (Australia led).
    """
    if not pbac_date or not nice_date:
        return None, None, "unknown"

    delta = (pbac_date - nice_date).days
    months = round(delta / 30.44, 1)

    if delta > 30:
        who_first = "NICE (UK first)"
    elif delta < -30:
        who_first = "PBAC (AUS first)"
    else:
        who_first = "Concurrent (±1mo)"

    return delta, months, who_first


# ── therapy area classification (mirrors generate_psd_data.py) ────────────────
THERAPY_KEYWORDS = {
    "Oncology": ["abemaciclib","abiraterone","acalabrutinib","afatinib","alectinib",
                 "atezolizumab","axitinib","bevacizumab","bortezomib","cabozantinib",
                 "carfilzomib","cetuximab","dabrafenib","daratumumab","dasatinib",
                 "durvalumab","enzalutamide","erlotinib","everolimus","gilteritinib",
                 "ibrutinib","imatinib","ipilimumab","isatuximab","ixazomib",
                 "larotrectinib","lenalidomide","lorlatinib","nivolumab","niraparib",
                 "obinutuzumab","olaparib","osimertinib","palbociclib","panitumumab",
                 "pazopanib","pembrolizumab","pertuzumab","ponatinib","ramucirumab",
                 "regorafenib","ribociclib","rucaparib","ruxolitinib","selpercatinib",
                 "sotorasib","sunitinib","talazoparib","trastuzumab","tucatinib",
                 "vandetanib","vemurafenib","venetoclax","zanubrutinib","sacituzumab",
                 "elranatamab","mirvetuximab","relatlimab","tebentafusp"],
    "Immunology": ["abatacept","adalimumab","baricitinib","belimumab","brodalumab",
                   "certolizumab","dupilumab","etanercept","filgotinib","golimumab",
                   "guselkumab","ixekizumab","infliximab","mepolizumab","natalizumab",
                   "ocrelizumab","risankizumab","rituximab","sarilumab","secukinumab",
                   "tezepelumab","tocilizumab","tofacitinib","upadacitinib","ustekinumab",
                   "vedolizumab","bimekizumab","mirikizumab","deucravacitinib"],
    "Rare Disease": ["burosumab","eculizumab","eliglustat","idursulfase","imiglucerase",
                     "laronidase","lumasiran","nusinersen","onasemnogene","ravulizumab",
                     "risdiplam","somatrogon","tezacaftor","ivacaftor","elexacaftor",
                     "vosoritide","ataluren","migalastat","avalglucosidase","cerliponase"],
    "Cardiovascular": ["alirocumab","evolocumab","ivabradine","sacubitril","vericiguat",
                       "edoxaban","apixaban","rivaroxaban","dabigatran","ticagrelor",
                       "inclisiran","bempedoic","icosapent"],
    "Neurology": ["dimethyl","fingolimod","glatiramer","ocrelizumab","ofatumumab",
                  "ozanimod","ponesimod","siponimod","teriflunomide","cladribine",
                  "eptinezumab","erenumab","fremanezumab","galcanezumab","lasmiditan",
                  "rimegepant","atogepant","nusinersen","onasemnogene","risdiplam"],
    "Diabetes": ["canagliflozin","dapagliflozin","dulaglutide","empagliflozin",
                 "exenatide","liraglutide","semaglutide","sitagliptin","tirzepatide",
                 "saxagliptin","linagliptin","ertugliflozin"],
    "Respiratory": ["benralizumab","budesonide","dupilumab","mepolizumab","omalizumab",
                    "reslizumab","roflumilast","tezepelumab","fluticasone","beclomethasone"],
}

def classify(drug: str) -> str:
    d = drug.lower()
    for area, kws in THERAPY_KEYWORDS.items():
        for kw in kws:
            if kw in d:
                return area
    return "Other"


# ── main ──────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Match PBAC PSDs with NICE TAs")
    parser.add_argument("--psd-dir",   default=str(PSD_DIR),   help="Folder containing PBAC PSDs")
    parser.add_argument("--nice-meta", default=str(META_PATH),  help="Path to nice_metadata.csv")
    parser.add_argument("--out-dir",   default=str(OUT_DIR),    help="Output folder for CSVs")
    args = parser.parse_args()

    psd_dir   = Path(args.psd_dir)
    meta_path = Path(args.nice_meta)
    out_dir   = Path(args.out_dir)

    log.info("=" * 65)
    log.info("PBAC ↔ NICE Matcher")
    log.info(f"PSDs      : {psd_dir}")
    log.info(f"NICE meta : {meta_path}")
    log.info(f"Output    : {out_dir}")
    if not FUZZY_AVAILABLE:
        log.info("  (Fuzzy matching disabled — run: pip install thefuzz python-Levenshtein)")
    log.info("=" * 65)

    # ── Load data ──────────────────────────────────────────────────────────
    pbac_records = parse_pbac_psds(psd_dir)
    nice_records = load_nice_metadata(meta_path)

    log.info(f"PBAC PSDs loaded : {len(pbac_records)}")
    log.info(f"NICE TAs loaded  : {len(nice_records)}")

    if not nice_records:
        log.error("No NICE metadata — run download_nice_missing.py first.")
        sys.exit(1)

    # ── Match ──────────────────────────────────────────────────────────────
    matched      = []
    pbac_only    = []
    matched_nice = set()   # ta_numbers that got matched

    for pr in pbac_records:
        nice_hits = match_drug(pr["drug"], nice_records)

        if not nice_hits:
            pbac_only.append(pr)
            continue

        # For drugs with multiple NICE TAs (e.g. nivolumab used in many cancers),
        # record each pair separately.
        for nr in nice_hits:
            gap_days, gap_months, who_first = date_gap(pr["pbac_date"], nr.get("nice_date"))

            matched.append({
                "drug":               pr["drug"],
                "therapy_area":       classify(pr["drug"]),
                "pbac_filename":      pr["filename"],
                "pbac_year":          pr["year"],
                "pbac_month":         pr["month"] or "",
                "pbac_date":          pr["pbac_date"].isoformat() if pr["pbac_date"] else "",
                "nice_ta_number":     nr["ta_number"],
                "nice_title":         nr.get("title", ""),
                "nice_published_date":nr.get("published_date", ""),
                "nice_date":          nr["nice_date"].isoformat() if nr.get("nice_date") else "",
                "nice_recommendation":nr.get("recommendation", ""),
                "gap_days":           gap_days if gap_days is not None else "",
                "gap_months":         gap_months if gap_months is not None else "",
                "who_moved_first":    who_first,
                "nice_guidance_url":  nr.get("guidance_url", ""),
            })
            matched_nice.add(nr["ta_number"])

    # NICE TAs with no PBAC match
    nice_only = [nr for nr in nice_records if nr["ta_number"] not in matched_nice]

    log.info(f"\nResults:")
    log.info(f"  Matched pairs  : {len(matched)}")
    log.info(f"  PBAC-only PSDs : {len(pbac_only)}  (no matching NICE TA)")
    log.info(f"  NICE-only TAs  : {len(nice_only)}   (no matching PBAC PSD)")

    # ── Summary stats ──────────────────────────────────────────────────────
    gaps = [r["gap_months"] for r in matched if isinstance(r["gap_months"], (int, float))]
    if gaps:
        avg_gap = round(sum(gaps) / len(gaps), 1)
        median_gap = sorted(gaps)[len(gaps) // 2]
        aus_lagged  = sum(1 for g in gaps if g > 1)
        aus_led     = sum(1 for g in gaps if g < -1)
        concurrent  = len(gaps) - aus_lagged - aus_led
        log.info(f"\nAccess gap analysis (positive = UK approved first):")
        log.info(f"  Average gap   : {avg_gap} months")
        log.info(f"  Median gap    : {median_gap} months")
        log.info(f"  UK first      : {aus_lagged} drugs")
        log.info(f"  AUS first     : {aus_led} drugs")
        log.info(f"  Concurrent    : {concurrent} drugs")

    # ── Save outputs ───────────────────────────────────────────────────────
    matched_fields = [
        "drug","therapy_area","pbac_date","nice_date","gap_days","gap_months",
        "who_moved_first","nice_recommendation","pbac_filename","nice_ta_number",
        "nice_title","nice_published_date","pbac_year","pbac_month","nice_guidance_url",
    ]

    matched_path = out_dir / "pbac_nice_matched.csv"
    with open(matched_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=matched_fields, extrasaction="ignore")
        w.writeheader()
        # Sort by drug name for readability
        w.writerows(sorted(matched, key=lambda r: r["drug"]))
    log.info(f"\nSaved: {matched_path}  ({len(matched)} rows)")

    pbac_only_path = out_dir / "pbac_nice_unmatched.csv"
    with open(pbac_only_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["drug","year","month","pbac_date","filename"],
                           extrasaction="ignore")
        w.writeheader()
        w.writerows(pbac_only)
    log.info(f"Saved: {pbac_only_path}  ({len(pbac_only)} rows)")

    nice_only_path = out_dir / "nice_pbac_unmatched.csv"
    with open(nice_only_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["ta_number","drug_name","title","published_date","recommendation","guidance_url"],
                           extrasaction="ignore")
        w.writeheader()
        w.writerows(sorted(nice_only, key=lambda r: r.get("drug_name","")))
    log.info(f"Saved: {nice_only_path}  ({len(nice_only)} rows)")

    log.info("")
    log.info("=" * 65)
    log.info("DONE — open pbac_nice_matched.csv in Excel to explore!")
    log.info("=" * 65)


if __name__ == "__main__":
    main()
