"""Build site_data.js — the single JS payload the dashboard consumes.

The build is intentionally a one-shot, top-level orchestration: each loader
produces a self-contained dict and we stitch them together. There's no
incremental diff or partial regeneration; the input data is small enough
(~1.9 MB output) that a full rebuild is fine and atomic.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime

from script_report.config import REPO_ROOT, SITE_DATA_JS
from script_report.data.loaders import (
    load_atc_data,
    load_pbac_psds,
    load_psd_extracted,
    load_drug_spend,
    load_pbac_calendar,
    load_pbac_agendas,
    load_psd_nearest,
    attach_nearest_to_psd,
    attach_agenda_drug_slugs,
    attach_sponsor_spend,
)


_SITE_DATA_SCRIPT_RE = re.compile(r'<script src="site_data\.js(?:\?v=[^"]*)?"></script>')


def _bust_index_html_cache(site_data_bytes: bytes) -> None:
    """Pin index.html to this build's site_data.js via a content-hash query string.

    Without this, Vercel's 1h cache on site_data.js can serve a browser an old
    payload paired with a fresh index.html — fields the new HTML reads can be
    missing from the stale JSON, silently rendering as 0/empty.
    """
    index_html = REPO_ROOT / "index.html"
    digest = hashlib.sha256(site_data_bytes).hexdigest()[:8]
    html = index_html.read_text(encoding="utf-8")
    new_html, n = _SITE_DATA_SCRIPT_RE.subn(
        f'<script src="site_data.js?v={digest}"></script>', html, count=1
    )
    if n == 0:
        print("  [warn] index.html: site_data.js script tag not found — skipping cache-bust")
        return
    if new_html != html:
        index_html.write_text(new_html, encoding="utf-8")
        print(f"  Pinned index.html → site_data.js?v={digest}")


def write_site_data(
    pbs: dict,
    pbac: dict,
    psd: dict,
    drug_spend: dict | None = None,
    calendar: dict | None = None,
    agendas: dict | None = None,
) -> None:
    """Compose the SITE_DATA payload and write site_data.js."""
    now = datetime.now().strftime("%Y-%m-%d")

    pbs_2024 = pbs["grand_total_by_year"].get("2024", 0)
    pbs_years_sorted = sorted(pbs["grand_total_by_year"].keys())
    earliest_val = pbs["grand_total_by_year"].get(pbs_years_sorted[0], 1) if pbs_years_sorted else 1
    pbs_growth = round(pbs_2024 / earliest_val, 1) if earliest_val else 0
    scripts_2024 = pbs["services_by_year"].get("2024", 0)

    site_data = {
        "generated": now,
        "stats": {
            "pbac_psds":    pbac["total"],
            "pbac_years":   pbac["year_range"],
            "pbs_2024_aud": pbs_2024,
            "pbs_growth_x": pbs_growth,
            "scripts_2024": scripts_2024,
        },
        "pbs": {
            "grand_total_by_year": pbs["grand_total_by_year"],
            "services_by_year":    pbs["services_by_year"],
            "classes_by_year":     pbs["classes_by_year"],
            "atc_meta":            pbs["atc_meta"],
        },
        "pbac":       pbac,
        "psd":        psd,
        "drug_spend": drug_spend or {"total": 0, "top_spend": [], "top_cost_per_script": [], "by_drug": {}},
        "calendar":   calendar or {"meetings": [], "last_updated": None, "last_milestone": None},
        "agendas":    agendas  or {"meetings": [], "n_meetings": 0, "n_items": 0, "last_updated": None},
    }

    js = (
        f"// site_data.js — auto-generated by python -m script_report build on {now}\n"
        "// Do not edit manually — re-run the build to regenerate.\n"
        f"window.SITE_DATA = {json.dumps(site_data, ensure_ascii=False, separators=(',', ':'))};\n"
    )

    SITE_DATA_JS.write_text(js, encoding="utf-8")
    print(f"  Written: site_data.js  ({SITE_DATA_JS.stat().st_size // 1024} KB)")
    _bust_index_html_cache(js.encode("utf-8"))


def main() -> None:
    """Run all loaders + write site_data.js. Print summary stats."""
    print("=" * 60)
    print("Building site_data.js")
    print("=" * 60)

    print("\n[1/7] Loading PBS ATC data...")
    pbs = load_atc_data()

    print("\n[2/7] Scanning PBAC PSDs...")
    pbac = load_pbac_psds()

    print("\n[3/7] Loading extracted PSD data...")
    psd = load_psd_extracted()

    print("\n[4/7] Loading PBS drug-level spend...")
    drug_spend = load_drug_spend()

    print("\n[5/7] Loading PBAC cycle calendar...")
    calendar = load_pbac_calendar()

    print("\n[6/7] Loading nearest-neighbour links (embed_psds.py output)...")
    nearest = load_psd_nearest()
    attach_nearest_to_psd(psd, nearest)

    print("\n[7/7] Loading upcoming PBAC + Intracycle agendas...")
    agendas = load_pbac_agendas()
    attach_agenda_drug_slugs(agendas, psd)

    print("\nJoining sponsor stats with PBS drug spend...")
    attach_sponsor_spend(psd, drug_spend)

    print("\nWriting output...")
    write_site_data(pbs, pbac, psd, drug_spend, calendar, agendas)

    # Pre-render static SEO landing pages from the freshly-built payload.
    # Importing inline avoids a circular dependency at module load time.
    print("\nPre-rendering static SEO pages...")
    from script_report.builders.prerenderer import generate_static_pages
    site_data_view = {"psd": psd, "drug_spend": drug_spend}
    stats = generate_static_pages(site_data_view, REPO_ROOT)
    print(f"  Drug pages    : {stats['drug_pages']} (avg {stats['avg_drug_kb']:.1f} KB)")
    print(f"  Sponsor pages : {stats['sponsor_pages']} (avg {stats['avg_sponsor_kb']:.1f} KB)")

    # ── Summary ──────────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("KEY STATS")
    print("=" * 60)
    pbs_years = sorted(pbs["grand_total_by_year"].keys())
    pbs_first = pbs_years[0]  if pbs_years else "n/a"
    pbs_last  = pbs_years[-1] if pbs_years else "n/a"
    v_first = pbs["grand_total_by_year"].get(pbs_first, 1) or 1
    v_last  = pbs["grand_total_by_year"].get(pbs_last, 0)
    print(f"  PBS total {pbs_first}  : ${v_first/1e9:.2f}B")
    print(f"  PBS total {pbs_last}  : ${v_last/1e9:.2f}B")
    print(f"  Growth             : {v_last/v_first:.1f}x")
    print(f"  Scripts 2024       : {pbs['services_by_year'].get('2024',0)/1e6:.1f}M")
    print(f"  PBAC PSDs          : {pbac['total']}")
    print(f"  Extracted drugs    : {psd['total']}")
    for rec, n in psd.get("by_recommendation", {}).items():
        print(f"    {rec:<35} {n}")
    print()
    print("  ATC classes in benefit data:")
    for atc, meta in sorted(pbs["atc_meta"].items(), key=lambda x: -x[1].get("spend_2024_aud", 0)):
        spend = meta["spend_2024_aud"]
        if spend > 0:
            print(f"    {atc[:50]:<50} ${spend/1e9:.2f}B (2024)")
    print()
    print("Done. Open index.html to see the updated site.")


if __name__ == "__main__":
    main()
